version: "3.8"

services:
  crawler:
    container_name: dockerdev
    image: atriiy/pool:latest
    ports:
      - "8000:8000"
    environment:
      DD_DB_HOST: db
    command: ./main
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: dockerdev-db
    image: redis:latest
    command: redis-server --requirepass redispw
    ports:
      - "6379:6379"
    networks:
      app:
        aliases:
          - redis

networks:
  app:
