name: pool

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test

    strategy:
      matrix:
        go-version: [ 1.19 ]
#       platform: [ ubuntu-latest, macos-latest, windows-latest ]
        platform: [ ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run tests
        run: go test -cover -tags test -race -timeout 30s ./...
